app:
  project_id: example
  env: test
  debug: false
  max_response_time: 5
  max_produce_retry_times: 3

zookeeper:
  hosts: localhost:12181
  timeout: 10.0
  topic_mapping_path: /event-bus-3/test/topics
  story_path: /event-bus-3/test/stories

# confluent_kafka:
#   https://docs.microsoft.com/en-us/azure/event-hubs/apache-kafka-configurations
#   https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
# aiokafka:
#   https://aiokafka.readthedocs.io/en/stable/api.html#consumer-class
kafka:
  producer:
    "bootstrap_servers": "maggie-kafka-1:9094,maggie-kafka-2:9094,maggie-kafka-3:9094"
    "enable_idempotence": "true"
    "acks": "all"

  consumer:
    "bootstrap_servers": ["maggie-kafka-1:9094", "maggie-kafka-2:9094", "maggie-kafka-3:9094"]
    "enable_auto_commit": false
    "auto_commit_interval_ms": 2000
    "auto_offset_reset": "latest"
    "max_poll_interval_ms": 600000 # offset commit failures because of rebalance
    "metadata_max_age_ms": 180000
    "heartbeat_interval_ms": 3000
    "session_timeout_ms": 60000 # If no hearts are received by the broker for a group member within the session timeout, the broker will remove the consumer from the group and trigger a rebalance.
    # "max_poll_records": 30

sentry:
  dsn: https://6fa26904f71d476ba73c9bfe1b54fe6e@sentry2.ideawisegroup.com/24

statsd:
  host: 10.20.2.118
  port: 8125
  prefix: eventbus3

#sinks:
#  test_sink:
#    url: http://localhost:8081/receive_events
#    timeout: 5
#
#stories:
#  - kafka_topic: "event-v2-test-topic1"
#    include_events: [ "test.event1", "test.event2" ]
#    exclude_events: [ "test.event3" ]
#    concurrent_per_partition: 1
#    dead_letter_topic: "event-v2-test-topic1-dl"
#    sink: test_sink
#
#topic_mapping:
#  - topic: event-v3-stress-test-4
#    patterns:
#      - stress_test\..*
#  - topic: event-v3-test-topic5
#    patterns:
#      - test\.event1
#  - topic: event-v3-test-default5
#    patterns:
#      - .*
