env: test
debug: false

default_kafka_config: # https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
  producer:
    "enable.idempotence": "true"
    "delivery.timeout.ms": "3000" # 3 seconds, default is "300000"
    "acks": "all"
    # "max.in.flight.requests.per.connection":  default is "1000000", after idempotence is "5"
    # "retries": default is "2147483647", after idempotence is INT32_MAX
    # "queue.buffering.max.messages": 100000
  consumer:
    "bootstrap.servers": "maggie-kafka-1:9094,maggie-kafka-2:9094,maggie-kafka-3:9094"
    "enable.auto.commit": "false"
    "auto.offset.reset": "latest"
    "max.poll.interval.ms": "50"

producers:
  p1:
    kafka_config:
      "bootstrap.servers": "maggie-kafka-1:9094,maggie-kafka-2:9094,maggie-kafka-3:9094"
      "enable.idempotence": "false"
      "compression.type": "none"
  p2:
    kafka_config:
      "bootstrap.servers": "maggie-kafka-1:9094,maggie-kafka-2:9094,maggie-kafka-3:9094"
      "compression.type": "gzip"

http_app:
  use_producers:
    producer_ids: [p1]
  max_response_time: 1

consumers:
  c1:
    kafka_topics: [ "topic1" ]
    kafka_config:
      "group.id": "group1"
      "max.poll.interval.ms": "300100"
    include_events: [test\..*]
    use_producers:
      producer_ids: [ p1 ]
    sink:
      url: http://localhost:8001
      method: POST
      timeout: 5
  c2:
    kafka_topics: [ "topic2" ]
    kafka_config:
      "group.id": "group2"
      "max.poll.interval.ms": "300080"
    include_events: [test2\..*]
    use_producers:
      producer_ids: [ p2 ]
    sink:
      url: http://localhost:8002
      method: POST
      timeout: 10

topic_mapping:
  - topic: primary-success
    patterns:
      - test\.primary-success
  - topic: secondary-success
    patterns:
      - test\.secondary-success
  - topic: event-v3-${env}-default
    patterns:
      - .*