env: test
debug: false

default_kafka_config:
  producer:
    "enable.idempotence": "true"
    "acks": "all"
    "max.in.flight.requests.per.connection": "5"
    "retries": "3"
    "delivery.timeout.ms": "2000" # 1 seconds
  consumer:
    "bootstrap.servers": "localhost:12811"
    "enable.auto.commit": "false"
    "auto.offset.reset": "latest"
    "max.poll.interval.ms": "50"

producers:
  p1:
    kafka_config:
      "bootstrap.servers": "localhost:12811"
      "enable.idempotence": "false"
      "compression.type": "none"
  p2:
    kafka_config:
      "bootstrap.servers": "localhost:12811"
      "compression.type": "gzip"

http_app:
  use_producers:
    producer_ids: [p1]
  max_response_time: 1

consumers:
  c1:
    kafka_topics: [ "topic1" ]
    kafka_config:
      "group.id": "group1"
      "max.poll.interval.ms": "300100"
    include_events: [test\..*]
    use_producers:
      producer_ids: [ p1 ]
    sink:
      url: http://localhost:8001
      method: POST
      timeout: 5
  c2:
    kafka_topics: [ "topic2" ]
    kafka_config:
      "group.id": "group2"
      "max.poll.interval.ms": "300080"
    include_events: [test2\..*]
    use_producers:
      producer_ids: [ p2 ]
    sink:
      url: http://localhost:8002
      method: POST
      timeout: 10

topic_mapping:
  - topic: primary-success
    patterns:
      - test\.primary-success
  - topic: secondary-success
    patterns:
      - test\.secondary-success
  - topic: event-v3-${env}-default
    patterns:
      - .*