[tool.isort]
profile = "black"
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
ensure_newline_before_comments = true
line_length=88
known_first_party="eventbus"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | pb2.py
    | \.pyi
    | protos
  )/
)
'''

[tool.pytest.ini_options]
addopts = "-rsxX -l --tb=short --strict-markers -v -m 'not integration and not benchmark'"
#addopts = "-rsxX -l --tb=short --strict-markers -v -s -m 'not integration and not benchmark'"
xfail_strict = true
testpaths = ["tests"]
markers = [
    "noconfig: Don't load the config.yml automatically",
    "integration: Integration tests",
    "benchmark: Benchmark tests",
]
asyncio_mode = "auto"

[tool.mypy]
files="eventbus,tests"
ignore_missing_imports=true

# https://microsoft.github.io/pyright/#/configuration?id=main-configuration-options
[tool.pyright]
include = ["eventbus", "tests"]
exclude = ["**/node_modules", "**/__pycache__"]
reportMissingImports = true
reportMissingModuleSource = true
reportOptionalSubscript = false
reportOptionalMemberAccess = false
useLibraryCodeForTypes = true
venvPath = "."
venv = "venv"
# verboseOutput = true
