apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventbus-producer-{comm}.fullname" . }}
  labels:
    {{- include "eventbus-producer-{comm}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "eventbus-producer-{comm}.selectorLabels" . | nindent 4 }}
