FROM python:3.9

WORKDIR /app

COPY requirements.txt ./
COPY requirements-ci.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install --no-cache-dir -r requirements-ci.txt

COPY . .
RUN pip3 install --no-cache-dir .