FROM python:3.8

WORKDIR /app

RUN pip3 install --no-cache-dir gunicorn uvicorn

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8000

COPY . .

ENTRYPOINT [ "/usr/local/bin/gunicorn", "eventbus.main_producer:app", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000", "-w", "1" ]