FROM python:3.8-slim-buster

WORKDIR /app

COPY . .

RUN pip3 install gunicorn uvicorn
RUN pip3 install .

EXPOSE 8000

ENTRYPOINT [ "/usr/local/bin/gunicorn", "eventbus.main_producer:app", "-k", "uvicorn.workers.UvicornWorker", "-b", "127.0.0.1:8000" ]