apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-3-consumer-deploy
  labels:
    app: event-bus-3
spec:
  selector:
    matchLabels:
      app: event-bus-3
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: event-bus-3
    spec:
      containers:
        - name: event-bus-3-consumer
          image: event-bus-3-consumer:latest
          command:
            - "-c /app-config/config.yml"
          volumeMounts:
            - name: event-bus-3-config-volume
              mountPath: /app-config
      restartPolicy: Always
      volumes:
        - name: event-bus-3-config-volume
          configMap:
            name: event-bus-3-config
            items:
              - key: config
                path: config.yml