apiVersion: v1
kind: Pod
metadata:
  name: event-bus-3-test
spec:
  containers:
    - name: test-container
      image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox
      command: [ "/bin/sh", "-c", "while true; do ls -l /configfiles; sleep 1; done" ]
      volumeMounts:
        - name: ec-volumn
          mountPath: /configfiles
  restartPolicy: Never
  volumes:
    - name: event-bus-3-config-volume
      configMap:
        name: event-bus-3-config
        items:
          - key: config
            path: config.yml