app:
  project_id: dev
  env: dev
  debug: false
  max_response_time: 5 #seconds

zookeeper:
  hosts: localhost:12181
  root_path: /event-bus-3/dev
  timeout: 10.0

v2_runners:
  all: [gpu01, ch06]

sentry:
  dsn: https://6fa26904f71d476ba73c9bfe1b54fe6e@sentry2.ideawisegroup.com/24

statsd:
  host: localhost
  port: 8125
  prefix: eventbus3.popp

default_kafka_params:
  producer:
    "bootstrap_servers": ["localhost:9092"]
    "enable_idempotence": "true"
    "acks": "all"

  consumer:
    "bootstrap_servers": ["localhost:9092"]
    "enable_auto_commit": false
    "auto_commit_interval_ms": 2000
    "auto_offset_reset": "latest"
    "max_poll_interval_ms": 600000 # offset commit failures because of rebalance
    "metadata_max_age_ms": 180000
    "heartbeat_interval_ms": 3000
    "session_timeout_ms": 60000 # If no hearts are received by the broker for a group member within the session timeout, the broker will remove the consumer from the group and trigger a rebalance.
