app:
  project_id: ${EB_COMM}
  env: lab
  debug: false
  max_response_time: 5 #seconds

zookeeper:
  hosts: 10.60.1.127:2181,10.60.1.128:2181
  root_path: /event-bus/${EB_COMM}/dev
  timeout: 10.0

v2_runners:
  all: [default-runner]

sentry:
  dsn: https://6fa26904f71d476ba73c9bfe1b54fe6e@sentry2.ideawisegroup.com/24

default_kafka_params:
  # https://aiokafka.readthedocs.io/en/stable/api.html#aiokafka.AIOKafkaProducer
  producer:
    "bootstrap_servers": ["maggie-kafka-1.thenetcircle.lab:9094", "maggie-kafka-2.thenetcircle.lab:9094", "maggie-kafka-3.thenetcircle.lab:9094"]
    "enable_idempotence": "true"
    "acks": "all"

  # https://aiokafka.readthedocs.io/en/stable/api.html#aiokafka.AIOKafkaConsumer
  consumer:
    "bootstrap_servers": ["maggie-kafka-1.thenetcircle.lab:9094", "maggie-kafka-2.thenetcircle.lab:9094", "maggie-kafka-3.thenetcircle.lab:9094"]
    "enable_auto_commit": false
    "auto_commit_interval_ms": 2000
    "auto_offset_reset": "latest"
    "max_poll_interval_ms": 600000 # offset commit failures because of rebalance
    "metadata_max_age_ms": 180000
    "heartbeat_interval_ms": 3000
    "session_timeout_ms": 60000 # If no hearts are received by the broker for a group member within the session timeout, the broker will remove the consumer from the group and trigger a rebalance.
